#pragma once

// forward declarations enum
typedef enum BinaryType BinaryType;
typedef enum CommandType CommandType;
typedef enum ContextType ContextType;
typedef enum EditorMode EditorMode;
typedef enum EditorAttr EditorAttr;
typedef enum ExceptType ExceptType;
typedef enum ErrorType ErrorType;
typedef enum FlagType FlagType;
typedef enum KeywordType KeywordType;
typedef enum NodeType NodeType;
typedef enum ProgramType ProgramType;
typedef enum TokenType TokenType;
typedef enum VariableType VariableType;

// forward declarations struct
typedef struct Array Array;
typedef struct AstNode AstNode;
typedef struct Atom Atom;
typedef struct Buffer Buffer;
typedef struct Context Context;
typedef struct DataToken DataToken;
typedef struct Debug Debug;
typedef struct Editor Editor;
typedef struct Error Error;
typedef struct Flags Flags;
typedef struct GarbageCollector GarbageCollector;
typedef struct History History;
typedef struct Input Input;
typedef struct Keyword Keyword;
typedef struct LexerState LexerState;
typedef struct Node Node;
typedef struct ReplState ReplState;
typedef struct Request Request;
typedef struct Response Response;
typedef struct SystemConfig SystemConfig;
typedef struct State State;
typedef struct StateContext StateContext;
typedef struct StateInput StateInput;
typedef struct Token Token;
typedef struct ValidationInput ValidationInput;

// forward struct Ast*
typedef struct AstArray AstArray;
typedef struct AstAssignment AstAssignment;
typedef struct AstBinary AstBinary;
typedef struct AstBinaryExpression AstBinaryExpression;
typedef struct AstBoolean AstBoolean;
typedef struct AstDeclaration AstDeclaration;
typedef struct AstDouble AstDouble;
typedef struct AstFloat AstFloat;
typedef struct AstIdentifier AstIdentifier;
typedef struct AstNumber AstNumber;
typedef struct AstProgram AstProgram;
typedef struct AstReturn AstReturn;
typedef struct AstString AstString;
typedef struct AstSubscript AstSubscript;
typedef struct AstVariable AstVariable;
typedef struct Assignment Assignment;
typedef struct ErrorInfo ErrorInfo;
typedef struct Symbol Symbol;
typedef struct SymbolTable SymbolTable;
typedef struct Args Args;
typedef struct Identifier Identifier;
typedef struct Function Function;
typedef struct Number Number;
typedef struct Binary Binary;
typedef struct Position Position;
