#pragma once

enum KeywordType {
  KEYWORD_NONE,
  KEYWORD_IF,
  KEYWORD_ELSEIF,
  KEYWORD_ELSE,
  KEYWORD_FOR,
  KEYWORD_REV,
  KEYWORD_WHILE,
  KEYWORD_PRINT,
  KEYWORD_IMPORT,
  KEYWORD_EXPORT,
  KEYWORD_EXTENDS,
  KEYWORD_RETURN,
  KEYWORD_BREAK,
  KEYWORD_CONTINUE,
  KEYWORD_ASYNC,
  KEYWORD_AWAIT,
  KEYWORD_CASE,
  KEYWORD_NULL
};
