#pragma once
/**
 * Definisi tipe yang digunakan untuk menentukan tipe
 * saat proses parsing menjadi AST.
 *
 * @NodeType
 */
enum NodeType {
  NODE_UNKNOWN = -1,
  NODE_ARRAY = 16,
  NODE_ASSIGN = 0,
  NODE_BOOLEAN = 1,
  NODE_BINARY = 2,
  NODE_ENDPROGRAM = 3,
  NODE_DECIMAL = 4,
  NODE_FUNCTION = 5,
  NODE_IDENTIFIER = 6,
  NODE_LITERAL_ID = 7,
  NODE_NUMBER = 8,
  NODE_NULLABLE = 9,
  NODE_PROGRAM = 10,
  NODE_PARAM = 11,
  NODE_RETURN = 12,
  NODE_STRING = 13,
  NODE_SUBSCRIPT = 14,
  NODE_STRUCT = 17,
  NODE_VARIABLE = 15,
  NODE_CALL = 18,
  NODE_PRINT = 19,
  NODE_BLOCK = 20,
  NODE_IF = 21,
  NODE_LOOP = 22,
  NODE_FUNCTION_DECL = 23,
  NODE_STRUCT_DECL = 24,
  NODE_ANNOTATION = 25,
  NODE_IMPORT = 26,
  NODE_EXPORT = 27,
  NODE_EXTENDS = 28,
  NODE_OBJECT = 29,
  NODE_ELSEIF = 30,
  NODE_ELSE = 31,
  NODE_BREAK = 32,
  NODE_CONTINUE = 33,
  NODE_UPDATE = 34,
  NODE_CONDITIONAL_ASSIGN = 35,
  NODE_THEN = 36,
  NODE_FALLBACK = 37,
  NODE_ASYNC = 38,
  NODE_AWAIT = 39,
  NODE_MEMBER = 40
};
