#pragma once

enum FlagType {
  FLAG_UNKNOWN = -1,
  FLAG_NONE,
  FLAG_AT,
  FLAG_ATOM,
  FLAG_ASSIGNMENT,
  FLAG_BACSLASH,
  FLAG_BRACE,
  FLAG_BRACKET,
  FLAG_COMMENT,
  FLAG_DOT,
  FLAG_FUNCTION_CALL,
  FLAG_FUNCTION_DECL,
  FLAG_HASH,
  FLAG_IDENTIFIER,
  FLAG_INVALID_NUMBER,
  FLAG_NEWLINE,
  FLAG_NUMBER,
  FLAG_PARENTHESIS,
  FLAG_OPERATOR,
  FLAG_SLASH,
  FLAG_STRING,
  FLAG_STRUCT_DECL,
  // Pending flag
  FLAG_PENDING,
  FLAG_POSSIBLE_ASSIGNMENT,
  FLAG_POSSIBLE_FUNCTION_DECL,
  FLAG_POSSIBLE_FUNCTION_CALL,
  FLAG_POSSIBLE_STRUCT_DECL,
  FLAG_WHITESPACE
};
