#pragma once

enum EditorMode { EDITOR_MODE_NORMAL, EDITOR_MODE_INSERT, EDITOR_MODE_COMMAND };
enum EditorAttr {
  EDITOR_ATTR_ARROW_UP,
  EDITOR_ATTR_ARROW_DOWN,
  EDITOR_ATTR_ARROW_LEFT,
  EDITOR_ATTR_ARROW_RIGHT,
  EDITOR_ATTR_BACKSPACE,
  EDITOR_ATTR_DELETE,
  EDITOR_ATTR_END,
  EDITOR_ATTR_ESCAPE,
  EDITOR_ATTR_HOME,
  EDITOR_ATTR_NONE
};
