#pragma once

enum ProgramType {
  PROGRAM_FUNCTION,
  PROGRAM_IDLE,
  PROGRAM_NAME,
  PROGRAM_OPEN_PAREN,
  PROGRAM_PARAMS,
  PROGRAM_CLOSE_PAREN,
  PROGRAM_OPEN_BRACE,
  PROGRAM_CLOSE_BRACE,
  PROGRAM_WAITING_BRACE,
  PROGRAM_COMPLETE,
  PROGRAM_PENDING,
  PROGRAM_UNKNOWN,
};
